runtime: go
api_version: go1

handlers:
- url: /connect
  script: _go_app

- url: /forward
  script: _go_app

- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/.*$